### ISSUE TITLE
Rebalance max fee based on profit margin (eg, LOOP)

### ISSUE THREAD

**Issue by pleb21** [itsneski/lightning-jet#12]
It would be nice to have the max ppm fees take profitability margin into account and adjust itself accordingly - instead of being fixed. While setting a overall max fee works for most channels, it fails in cases where the fee rate is too high. As it should in order to limit the total cost. 

LOOP is one such example where my fee (lc_rate) is high enough that it would make sense(profitable) to re-balance it with even a higher fee than the current 500ppm - it should start with lowest fee possible and in case it fails because of low fees, should try with a higher fee rate as long as it is profitable to do so, taking `rebalance fee` & `fee earning opportunity` for the amount being rebalanced.

**Comment by itsneski** [comment]
rebalancer now takes rebalance margin into account when setting the max fee.  it'll print out a message in /tmp/autorebalance.log when the margin is negative or below peer's fees. e.g:

rebalace margin: 50
rebalance margin is below remote peer's fees, revisit your fees: { base: 1, rate: 175 }
