### ISSUE TITLE
Jet monitor displays rebalances in progress > pending htlcs

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#16]
Somehow a strange display behaviour in jet monitor as pending htlcs are lower than rebalances in progress

<img width="966" alt="Screenshot 2021-11-06 at 10 20 37" src="https://user-images.githubusercontent.com/33904339/140604917-4fd0907c-7fb4-45c0-891d-9bb7684d7b4c.png">
.

**Comment by itsneski** [comment]
Those are probes, basically fake payments in an attempt to discover a route. So the delta between rebalances in progress and pending htlcs are the probes. Same as with the delta between lncli listinvoices --pending_only | grep 'Rebalance' and pending htlcs.

**Comment by itsneski** [comment]
To be discussed further at https://www.clubhouse.com/event/xoyvWYO1

**Comment by itsneski** [comment]
Addressed during the CH room discussion.
