### ISSUE TITLE
analyze-fees spiral due to fee update by peer

### ISSUE THREAD

**Issue by pleb21** [itsneski/lightning-jet#17]
More than an issue, this is an observation. I have an outbound peer (as per `jet peers`) with which the fee structure was very low - 80(fees set by peer)/87(fees set by me); this was the case until recently, my peer increased their fee to 150 and `analyze-fees` suggested I increase mine to 201; after some time it suggested me to increase it to 501 (as the peer had increased to 450); so it went and now we are at 1050/1201ppm from 80/87ppm. Incidentally, the peer also happens to use jet and likely increased the fees based on their results/suggestions of `analyze-fees`

This primarily is due to the fact that the peer increased their fee (manually or because of some tool which may have done this). How should the analyze-fees work in such cases to prevent such a situation?

**Comment by itsneski** [comment]
Updated jet analyze-fees. It now warns about an increase in peers' fees and recommends waiting for peer to update their  fees. This will help better adapt to remote peers' fee updates.
