### ISSUE TITLE
git pull fails with error: Your local changes to the following files would be overwritten by merge:  package-lock.json

### ISSUE THREAD

**Issue by itsneski** [itsneski/lightning-jet#18]
```
git pull
Updating 7f23daa..cad71b1
error: Your local changes to the following files would be overwritten by merge:
 package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```

Workaround: `git checkout -- package-lock.json`, then retry `git pull`

**Comment by itsneski** [comment]
.gitignore will be added as part of the next git push:
package-lock.json
api/config.json
db/jet.db
node_modules/

**Comment by Deekee62** [comment]
Very good idea 👍

**Comment by itsneski** [comment]
fixed in https://github.com/itsneski/lightning-jet/commit/98da1d3c9299a788865d66700f1a707eb8a50870.
