### ISSUE TITLE
Multiple misspelling in instructions

### ISSUE THREAD

**Issue by junseth** [itsneski/lightning-jet#19]
"To create jet bot: initiate a converation with BotFarther on your Telegram app. Select bot's name (e.g. JET bot) and bot's username (e.g. jet_bot)."

Should read: "To create jet bot: initiate a conversation with BotFather on your Telegram app. Select bot's name (e.g. JET bot) and bot's username (e.g. jet_bot)."

**Comment by itsneski** [comment]
The current & the proposed versions seem to be the same.

**Comment by junseth** [comment]
converation and BotFarther
vs
conversation and BotFather

**Comment by itsneski** [comment]
Fixed, will be uploaded in the next version.
