### ISSUE TITLE
SQLITE busy: database is locked

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#2]
While a single circular rebalance was in progress, I did a dry run using autorebalance.js

`node service/autorebalance.js --dryrun`

The circular rebalance finished successfully...

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/33904339/138582506-7506c35b-5e81-4793-a9f3-ad0258ef880b.png">

... but the following error was reported:

![telegram-cloud-photo-size-4-6026268093782800209-y](https://user-images.githubusercontent.com/33904339/138582527-c26e9dc1-3d7c-43fa-962f-8b47a06cae9b.jpg)

Output of autorebalance:
[autorebalance.log](https://github.com/itsneski/lightning-jet/files/7404145/autorebalance.log)

**Comment by itsneski** [comment]
fixed
