### ISSUE TITLE
jet monitor change of timestamp

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#27]
May I recommend to change the following timestamps to 24 hour format since it is not evident whether it's AM or PM

rebalances in progress:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/33904339/143068521-04130d3f-4ee1-4678-87cb-55d6d426e525.png">

successful rebalances over the past 4 hour(s) (10 max lines):

<img width="183" alt="image" src="https://user-images.githubusercontent.com/33904339/143068876-bc81bc5d-fd8d-4ece-b73e-e45bb7d811ad.png">

**Comment by itsneski** [comment]
Will be addressed in the next git push.
