### ISSUE TITLE
Telegram wrongly reports channel.db exceeds 5GB

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#31]
Telegram reports `channel.db size 4,953 gb exceeds 5 gb` but it's not.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/33904339/143836519-43cf8172-448a-42c3-bd36-0a78cd60ecac.png">

`du -h ~/umbrel/lnd/data/graph/mainnet/channel.db` reports a size of 4.7 GB

**Comment by itsneski** [comment]
jet uses (https://www.geeksforgeeks.org/node-js-fs-statsync-method/)[statSync] method to determine files size. it is equivalent to `ls -l`, which will return the actual file size in bytes as opposed to `du -h` which shows disk usage. try `ls -l` instead to see if it returns the same size as jet.

**Comment by itsneski** [comment]
The fix to the issue where it says that 4,953 exceeds 5gb will be part of the next git push.

**Comment by itsneski** [comment]
Corrected message:
channel.db size 4,953 gb exceeds 2 gb
familiarize yourself with compacting & pruning procedure: https://plebnet.wiki/wiki/Compacting_Channel_DB
