### ISSUE TITLE
Misleading summary in jet monitor --status

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#36]
The summary shown on index 12 + 13 is:

`'remote ppm exceeds local. revisit local ppm and / or max ppm based on suggested range'`

But local ppm is 200 ppm higher than remote ppm and maxAutoPpm is set to 550 in config.json.

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/33904339/145954994-59dd1e2b-446c-47a2-ba8e-0f40b2d4cf8c.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/33904339/145956972-3ee07501-6b59-4ad6-8ca2-7f2b43f23d9d.png">

<img width="867" alt="image" src="https://user-images.githubusercontent.com/33904339/145957070-c650e7d1-cb68-4d9a-9705-e2203913b7a9.png">

**Comment by itsneski** [comment]
Will be addressed in the next git push.
