### ISSUE TITLE
Wrong display in jet monitor

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#39]
I did the following manual rebalance using the following command:

`jet rebalance 'BTC Sessions' 024706bbb0ef2a7dda56 500000 `

... and it seemed to have started successfully!

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/33904339/147105332-80459dc7-436c-4bd6-af17-cfefbf005376.png">

But unfortunately the display in  jet monitor` is some how wrong, as it doesn't show the peer balanced into, instead it shows  a part of the peer name balancing from, it seems that the white space in the peer alias is causing the issue.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/33904339/147105422-8f370105-e86f-4bb5-ba8d-3f6a5e37459d.png">

**Comment by itsneski** [comment]
jet monitor incorrectly reads the stats from rebalance process. This will be addressed in the next git push.
