### ISSUE TITLE
Annoying reminders in Telegram when channel.db > 7 GB

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#41]
I think it's very annoying to receive a reminder every 5 minutes and it spams telegram unnessecarily!

Personally an hourly one would be sufficient and a symbol ⚠️ could be added to give it more expression!

Maybe also an option in `config.json` could be made to set the interval manually...

<img width="829" alt="image" src="https://user-images.githubusercontent.com/33904339/147637575-fd688b31-5779-4e74-8d61-0dfcb82b6427.png">

**Comment by itsneski** [comment]
As a workaround edit `api/constants.js`, on line 70 change `urgent: 5 * 60` to `urgent: 60 * 60`.  this will set it to an hour. then `jet restart daddy`.

you'll need to `git checkout -- api/constants.js` prior to `git pull`.

**Comment by Deekee62** [comment]
Thanks for the quick workaround :-)
