### ISSUE TITLE
Add documentation for docker

### ISSUE THREAD

**Issue by Cameri** [itsneski/lightning-jet#45]
Currently there's no documentation for docker on:
- how to build the docker image from source
- how to publish (git tags?)
- how to run with mynode
- how to run with raspiblitz
- how to run with umbrel
- how to run with native setup
- how to run commands on docker container

**Comment by itsneski** [comment]
fixed in https://github.com/itsneski/lightning-jet/commit/c2737140c899b984bbd1fcc0267c858dd3f54e61.
