### ISSUE TITLE
Add exponential backoff after failed rebalance

### ISSUE THREAD

**Issue by Cameri** [itsneski/lightning-jet#46]

**Comment by itsneski** [comment]
for things like peers being offline, or not having enough liquidity to rebalance, the rebalancer won't even try. with respect to the fee being too high, it excludes the node with the highest fee on the route and retries. if still no routes are found, it returns feetoohigh error. liquidity constantly shifts, so retrying in case of feetoohigh error makes sense without backoff. the only case where backoff might be applicable is failedtofindpath error, which basically means there is no route available to the peer atm.

**Comment by Cameri** [comment]
let's close this for now until there's actual demand for it

**Comment by itsneski** [comment]
will be part of the next git push

**Comment by itsneski** [comment]
addressed in https://github.com/itsneski/lightning-jet/commit/13b1c5393326936976fa3276759ec3a6da31edb3.
