### ISSUE TITLE
Jet rebalance-history printing blank table when a node is specified

### ISSUE THREAD

**Issue by ZeddOps** [itsneski/lightning-jet#50]
zombie:~$ uname -a
Linux zombie 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

zombie:~$ jet rebalance-history c-otto.de
rebalance history for c-otto.de
┌─────────┐
│ (index) │
├─────────┤
└─────────┘

**Comment by itsneski** [comment]
The issue is reproduced when no --hours parameter is specified
<img width="729" alt="Screen Shot 2022-01-04 at 11 52 44 PM" src="https://user-images.githubusercontent.com/91937527/148180632-1c6031ed-56d0-4c39-908a-c8ae543f95d6.png">
.
