### ISSUE TITLE
jet monitor "stuck htlcs"

### ISSUE THREAD

**Issue by Deekee62** [itsneski/lightning-jet#7]
I find the naming "stuck htlcs" a kind of confusing, may I suggest to rename it to "active htlc's" :-)

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/33904339/139463968-ab222de4-e86e-4d76-8fe7-6f955fa15e52.png">

**Comment by itsneski** [comment]
Thanks for this issue.  This will be addressed in the next update.  Currently leaning towards pending htlcs, as that's the term that is being used in lncli listchannels.

**Comment by itsneski** [comment]
Fixed.
