### ISSUE TITLE
File search code appears to truncate path

### ISSUE THREAD

**Issue by rsafier** [itsneski/lightning-jet#71]
Setup jet on a BTCPayServer where files live in  /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/
Noticed in monitor output that some things were truncated 
![image](https://user-images.githubusercontent.com/645964/158045136-a065551d-eb96-4394-9b73-13ef28332415.png)

**Comment by itsneski** [comment]
jet attempts to locate channel.db under the lnd folder. it incorrectly truncates the file path when trying to set the base folder for the search. not a critical error, it affects channel.db size notifications in telegram and `jet monitor`.
