### ISSUE TITLE
Jet fails when you have a private channel

### ISSUE THREAD

**Issue by dannydeezy** [itsneski/lightning-jet#81]
I have a private channel with a node, and running `jet monitor` fails with this error:
```
getNodesInfo: 035590592cefc01a34c82db9fcedb35af1b9d103a2033eb3c0befd7c8ea9af99b6, error: Error: 5 NOT_FOUND: unable to find node
/home/ubuntu/lightning-jet/lnd-api/utils.js:345
      peerInfo[p.node.pub_key] = p;
```

i also suspect other jet processes are blocked due to this error but I'm not sure how to check and see. Most other calls are failing with a similar error too

**Comment by itsneski** [comment]
I'll test/verify it with private channels.

To check the logs of jet processes, run jet status, it'll show you the location of log files.

**Comment by itsneski** [comment]
tested with a private channel, could not repro.  new repro detail - the peer was offline.  checked on amboss.space, the node with this id does not exist, which is what likely caused the issue.

fix: make sure that getNodesInfo does not exit if one node errors out.
