### ISSUE TITLE
Disable auto balancing

### ISSUE THREAD

**Issue by kroese** [itsneski/lightning-jet#82]
Is there any option to disable the auto balancer? For example, if you use it just for analyze-fees or some other function.

One workaround I can think of is to raise the minimal required channelsize to a very high number so that all channels get excluded, but it would be nicer to just have a dedicated flag for this.

**Comment by itsneski** [comment]
https://github.com/itsneski/lightning-jet#config-file, exclude setting under rebalancer section allows you to disable rebalancer for individual peers. to disable the rebalancer for all peers, you will need to stop the main process and the rebalancer:

```jet stop daddy
jet stop rebalancer
```

**Comment by itsneski** [comment]
rebalancer won't be running when the container is restarted unless you made the main process (daddy) a system daemon that automatically starts upon system restart.

with that being said, there is a use case when the rebalancer needs to be disabled while other services (logger, telegram) are running. i will introduce an explicit `disable` flag under the rebalancer config section.

for now, make sure that daddy & rebalancer services aren't running (by simply not starting them in the container).

**Comment by itsneski** [comment]
I presume you started the container as in https://github.com/itsneski/lightning-jet#start-up-daddy, correct? this will start up the daddy process. so the `disable` flag is needed in this case to ensure that the rebalancer isn't running. the flag will be introduced in the upcoming release (1.4.4).

in the meantime, the workaround is to stop daddy and rebalancer manually.

**Comment by itsneski** [comment]
part of https://github.com/itsneski/lightning-jet/releases/tag/v1.4.4-embassy
