### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by kroese** [itsneski/lightning-jet#83]
When I have the lightning-jet docker container configured for "host" networking it works. But when I change it to "umbrel_main_network" (Bridged) networking, it cannot connect to 10.21.21.9:

```
isLndAlive: error calling getInfo Error: 14 UNAVAILABLE: No connection established

lnd is offline
```
I am trying to understand why this is. Because all my other containers are able to reach the LND node container using bridged networking. So what does Jet do differently?

**Comment by itsneski** [comment]
jet uses grpcs's implementation (node.js) of https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.proto to connect to lnd, a rather standard way to connect to lnd.

are you able to successfully ping the host?

**Comment by itsneski** [comment]
has the issue been resolved?

jet uses a couple of different ways to connect to lnd:

https://github.com/itsneski/lightning-jet/blob/main/lnd-api/connect.js - via combineChannelCredentials
https://github.com/itsneski/lightning-jet/blob/main/bos/connect.js - via authenticatedLndGrpc

both are standard lnd API calls.

one way to debug this further is to build a test tool on top of these calls to spit out debug info.  would be happy to provide.

**Comment by itsneski** [comment]
jet uses serverAddress config setting or localhost if not specified. It
should work as long as serverAddress matches the lnd hostname in jet
docker's .env.

I'll add display of the hostname that jet is connecting to.

**Comment by itsneski** [comment]
serverAddress in the config overrides default localhost. then the lnd
hostname in .env is mapped to an IP. so you do need both.
