### ISSUE TITLE
Running "jet monitor" against voltage.cloud returns async hook corruption Error

### ISSUE THREAD

**Issue by itshig** [itsneski/lightning-jet#85]
services:
┌─────────┬──────────────┬───────────┬────────────────────────┐
│ (index) │   service    │  status   │          log           │
├─────────┼──────────────┼───────────┼────────────────────────┤
│    0    │ 'rebalancer' │ 'stopped' │ '/tmp/rebalancer.log'  │
│    1    │   'logger'   │ 'stopped' │ '/tmp/htlc-logger.log' │
│    2    │   'daddy'    │ 'running' │  '/tmp/launcher.log'   │
│    3    │  'telegram'  │ 'running' │  '/tmp/telegram.log'   │
└─────────┴──────────────┴───────────┴────────────────────────┘
Error: async hook stack has become corrupted (actual: 1188, expected: 1)
 1: 0xa8d14d node::AsyncHooks::FailWithCorruptedAsyncStack(double) [node]
 2: 0xa42c58 node::InternalCallbackScope::Close() [node]
 3: 0xa42f71 node::InternalCallbackScope::~InternalCallbackScope() [node]
 4: 0xacaf52 node::StartExecution(node::Environment, std::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [node]
 5: 0xa467e7 node::LoadEnvironment(node::Environment, std::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [node]
 6: 0xb4bd95 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
 7: 0xacd592 node::Start(int, char**) [node]
 8: 0x7f67eae5a083 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xa4067c  [node]

**Comment by itsneski** [comment]
reproduced on a test instance

**Comment by itsneski** [comment]
fix will be part of the upcoming jet release
