### ISSUE TITLE
Rebalancer Not Working (ERR in lnd.log: permission denied)

### ISSUE THREAD

**Issue by LightningLuke** [itsneski/lightning-jet#86]
I recently noticed jet rebalancer was not auto rebalancing despite it running. It had been working phenomenally up until a few weeks ago. I looked into it further by checking my lnd logs. lnd.log file was spammed with the following error
`[ERR] RPCS: [/routerrpc.Router/SendToRouteV2]: permission denied` 

Just a few days ago I turned off jet rebalancer and this "permission denied" error in the lng.log file has since stopped.

Checked into the peer specific rebalancer logs in /tmp dir and noticed a couple different errors. I'm not sure if they're related or not, but here they are in case it helps. Important note here, though, `bos rebalance` still continues to work normal in isolation.
```
unidentified error {
  "code": 503,
  "error": "UnexpectedErrorWhenPayingViaRoute",
  "original": [
    503,
    "UnexpectedErrorWhenPayingViaRoute",
    {
      "err": {
        "code": 2,
        "details": "permission denied",
        "metadata": {
          "content-type": [
            "application/grpc"
          ]
        }
      }
    }
  ]
}  exiting
```

and then the bos rebalance error:
```
bos rebalance error: {
  "err": [
    503,
    "UnexpectedErrorWhenPayingViaRoute",
    {
      "err": {
        "code": 2,
        "details": "permission denied",
        "metadata": {
          "content-type": [
            "application/grpc"
          ]
        }
      }
    }
  ]
}
```

**What Versions I am on Currently**
`lncli --version`
0.14.3-beta

`jet -V`
1.4.4

`bos --version`
12.13.2

**Comment by itsneski** [comment]
jet is using an older bos package in package.json (to call probes), likely needs to be updated to fix this

**Comment by itsneski** [comment]
this is working on the latest umbrel install that has lnd 0.14.2.  it looks like this issue is specific to lnd 0.14.3.

**Comment by itsneski** [comment]
note: this issue is specific to running jet on parallels ubuntu vm: `Linux parallels-Parallels-Virtual-Platform 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`.

installed the latest update from dev branch. jet rebalance is working (good sign), but rebalance service fails to spawn processes. i suspect this issue is specific to the parallels vm.

installed a parallels ubuntu vm to research this further, https://www.parallels.com/tips/windows-on-mac/linux/.

**Comment by itsneski** [comment]
repro'd this issue with jet running on umbrel, managing lnd15 node in voltage.cloud. same issue as with jet running on mac or parallels VM. jet peers, jet rebalance, and other utilities are working when invoked manually, with rebalances failing due to `No connection established` error when spawned as individual processes by the rebalancer:

```
/home/umbrel/test/lightning-jet/lnd-api/utils.js:390
        throw new Error(err);
        ^

Error: Error: 14 UNAVAILABLE: No connection established
    at Object.callback (/home/umbrel/test/lightning-jet/lnd-api/utils.js:390:15)
    at Object.onReceiveStatus (/home/umbrel/test/lightning-jet/node_modules/@grpc/grpc-js/build/src/client.js:189:36)
    at Object.onReceiveStatus (/home/umbrel/test/lightning-jet/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/home/umbrel/test/lightning-jet/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/umbrel/test/lightning-jet/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
    at Function.module.exports.runLoopOnce (/home/umbrel/test/lightning-jet/node_modules/deasync/index.js:64:10)
    at Object.listChannelsSync (/home/umbrel/test/lightning-jet/lnd-api/utils.js:395:26)
    at Object.listPeersSync (/home/umbrel/test/lightning-jet/lnd-api/utils.js:349:35)
```

**Comment by itsneski** [comment]
observed permission denied error when connecting to my node running lnd14.1 node via 53.17.4 ln-service that is part of 12.16.1 bos; grpc-js has been updated to 1.6.8. the issue went away with admin.macaroon. i presume a change in the grpc comms requires admin.macaroon from now on.
