### ISSUE TITLE
lnd connect error for nodes in voltage.cloud

### ISSUE THREAD

**Issue by itsneski** [itsneski/lightning-jet#89]

**Comment by itsneski** [comment]
observed in the daddy log, /tmp/launcher.log, as well as in the individual rebalances. does not occur when rebalances are launched from command line via `jet rebalance ...`

**Comment by itsneski** [comment]
the issue is reproduced when the main process and the [detached] child process open their separate grpc connections. perhaps there is a limit on the number of grpc connections that can be opened to a voltage.cloud node. double-checking with support.

**Comment by itsneski** [comment]
this issue does not occur on umbrel 0.5.x running lnd15, it seems to be specific to nodes in voltage.cloud.

**Comment by gkrizek** [comment]
Can you post what errors you see exactly? I'm trying to reproduce and investigate but want to make sure I'm seeing the same issues you are seeing. Thanks!

**Comment by itsneski** [comment]
> Can you post what errors you see exactly? I'm trying to reproduce and investigate but want to make sure I'm seeing the same issues you are seeing. Thanks!

The following error is received:

`Error: 14 UNAVAILABLE: No connection established`

LND API getInfo call via grpc-gs v1.6.8 (with 0.7.0 proto-loader). Process A makes getInfo call, which is successful, then spawns process B which makes the same call that fails with the above error. Both processes created their separate grpc handles via `new lnrpc.Lightning`. The error does not occur when process A just spawns process B without making getInfo call.

**Comment by itsneski** [comment]
update from Graham: voltage team will likely look at this issue this week.

**Comment by itsneski** [comment]
fixed in https://github.com/itsneski/lightning-jet/releases/tag/v1.5.1-metrics
