### ISSUE TITLE
Rebalancer uses an excluded peer for rebalancing

### ISSUE THREAD

**Issue by bcomingsuperfly** [itsneski/lightning-jet#97]
Issue: Rebalancer uses an excluded peer to rebalance.

Expected result: Using "exclude" in the config would prevent rebalancer from using that peer as excluded in all circumstances.

Description:

The following line is in config.json referencing peer "LOOP":
"exclude": ["021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d:outbound"]

The peer "LOOP" should not be used for rebalancing OUT. Although recognized in tail -2000 /tmp/jet-rebalancer.log as a valid exclusion, rebalancer continues to rebalance OUT the excluded node and into another peer.

Rebalancer classifies this excluded peer as an "Inbound" peer and does not prevent the rebalance.

Recommend adjusting the algo to force exclusions. Alternatively, permit the user to change the classification given to a peer (example: although Loop is considered an "Inbound" peer I could correct that to identify it as an "Outbound" peer).

**Comment by itsneski** [comment]
loop was classified inbound by jet based on routing. jet rebalances from inbound to outbound peers, hence liquidity was rebalanced from loop.

make a change in the rebalancing algo to make sure that no outbound routing is done based on exclude.

**Comment by itsneski** [comment]
add telegram warning if exclude is malformed.

**Comment by itsneski** [comment]
after applying :inbound exclude to LOOP, jet correctly excluded it from auto rebalancing, preventing liquidity to be drawn out of it:

`021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d LOOP excluded based on settings`

despite the change, LOOP still showed up in the rebalance, from LOOP -> bfx-lnd0. closer look at the logs shows that this was rebalance in response to a forward:

`[forward] from: LOOP 021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d to: bfx-lnd0 033d8656219478701227199cbd6f670335c8d408a92ae88b962c49d4dc0e83e025 sats: 753017`

jet rebalances in follow-up to forwards to restore liquidity. further code analysis showed that exclude clause is not currently applied to this case, and it should.

**Comment by itsneski** [comment]
https://github.com/itsneski/lightning-jet/releases/tag/v1.5.5-exclude
